# Bibliotecas utilizadas

In [30]:
import pandas as pd
import json
import requests

# 📌 Extracão

In [28]:
# with open('TelecomX_Data.json','r') as f:
#     dados = json.loads(f.read())


# df = pd.read_json(dados)

# df_norm = pd.json_normalize(df, record_path='customer')

In [16]:
df.head(1)

,customerID,Churn,customer,phone,internet,account
0,0002-ORFBO,No,"{'gender': 'Female', 'SeniorCitizen': 0, 'Part...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'One year', 'PaperlessBilling': '..."

In [18]:
df_norm.head()

,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies
0,DSL,No,Yes,No,Yes,Yes,No
1,DSL,No,No,No,No,No,Yes
2,Fiber optic,No,No,Yes,No,No,No
3,Fiber optic,No,Yes,Yes,No,Yes,Yes
4,Fiber optic,No,No,No,Yes,Yes,No

In [ ]:
# Obtendo o arquivo json da API

dados_usuarios = requests.get('https://github.com/ingridcristh/challenge2-data-science/blob/main/TelecomX_Data.json')
resultado = json.loads(dados_usuarios.text)
pd.DataFrame(resultado)

NameError: name 'TelecomX_Data' is not defined

# 🔧 Transformação

# 📊 Carga e análise

# 📄Relatorio Final